site_name: High Performance Computing for Digital Humanities
site_description: High Performance Computing for Digital Humanities
site_author: KCL e-Research
site_url: 'https://kcl-eresearch.github.io/High-Performance-Computing-for-Digital-Humanities'
repo_url: 'https://github.com/kcl-eresearch/High-Performance-Computing-for-Digital-Humanities'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - meta
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

theme:
  name: material
  locale: en
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.top
  custom_dir: theme/

nav:
    - Intro: 'index.md'
    - Connecting: 'connecting.md'
    - Accessing software: 'using_software.md'
    - Submitting jobs: 'submitting_jobs.md'
    - Parallel jobs: 'parallel_jobs.md'
    - Singularity: 'singularity.md'
    - Jupyter notebooks: 'jupyter.md'
    - Practical: 'exercises.md'
    - Next steps: 'next-steps.md'
    - Reference:
      - Unix commands: 'unix_commands.md'
      - SSH keys: 'ssh_keys.md'
    - Slides: 'slides/index.html'
